name: Build and test NGAS
on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
        - python: 3.6
        - python: 3.7

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup hostname
      run: sudo hostname my-ngas-host

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install core python development packages
      run: pip install -U pip setuptools wheel

    - name: Install system dependencies
      run: sudo apt update && sudo apt install libdb-dev

    - name: Install NGAS
      run: VIRTUAL_ENV=${pythonLocation} SKIP_BBCP=1 TRAVIS_BUILD_DIR=$PWD .travis/run_build.sh

    - name: Run NGAS tests
      run: TESTS=test/test_mime_multipart.py .travis/run_tests.sh

    - name: Upload coverage results
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true

  upload-coverage:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Update coverage
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
