name: Build and test NGAS
on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
        - python: 3.7

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup hostname
      run: sudo hostname my-ngas-host

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install core python development packages
      run: pip install -v -U pip setuptools wheel

    - name: Install system dependencies
      run: sudo apt update && sudo apt install libdb-dev

    - name: Install NGAS
      run: SKIP_BBCP=1 TRAVIS_BUILD_DIR=$PWD .travis/run_build.sh

    - name: Run NGAS tests
      run: .travis/run_tests.sh

    - name: Upload coverage results
      run: .travis/after_success.sh
